export enum NewsTheme {
  POLITICAL_MAP = 'POLITICAL_MAP',
  ECONOMY = 'ECONOMY',
  PUBLIC_INTEREST = 'PUBLIC_INTEREST',
  SCIENCE_AND_EDUCATION = 'SCIENCE_AND_EDUCATION',
  CULTURAL_SPACE = 'CULTURAL_SPACE',
}
