import { List } from 'immutable'

import { Region } from '../../../../src/iviche/common/Region'
import { Theme } from '../../../../src/iviche/common/Theme'
import { PollDTOTuple } from '../../../../src/iviche/polls/dto/PollDTOTuple'
import { Poll } from '../../../../src/iviche/polls/models/Poll'
import { PollAnswerStatus } from '../../../../src/iviche/polls/models/PollAnswerStatus'
import { PollStatus } from '../../../../src/iviche/polls/models/PollStatus'
import { PollType } from '../../../../src/iviche/polls/models/PollType'
import { publicUserData } from '../../../i9n/common/TestUtilities'

const DTOPollData = {
  anonymous: true,
  complexWorkflow: false,
  authorUID: publicUserData.uid,
  authorIsLegalPerson: false,
  authorFirstName: 'John',
  authorLastName: 'Rich',
  authorShortName: null,
  authorAvatar: null,
  status: PollStatus.MODERATION,
  taAddressRegion: Region.KHARKIV_REGION,
  tags: [],
  taGenders: [],
  taAgeGroups: [],
  competencyTags: [],
  taSocialStatuses: [],
  theme: Theme.AGRICULTURE,
  votingStartAt: new Date('01.02.2020'),
  votingEndAt: new Date('02.02.2020'),
  answersCount: 0,
  votesCount: 0,
  commentsCount: 0,
  isHidden: false,
  pollType: PollType.REGULAR,
}

export const pollDTOList: Array<PollDTOTuple> = [
  {
    ...DTOPollData,
    uid: '00000000-aaaa-aaaa-aaaa-000000000001',
    title: 'Test title of poll #1 (created poll)',
    body: 'Test perfect body of poll #1 (created poll)',
    answerUid: '00000000-aaaa-aaaa-aabb-000000000001',
    answerTitle: 'test answer title',
    answerBasic: true,
    answerStatus: PollAnswerStatus.MODERATION,
    answerAuthorUID: publicUserData.uid,
    answerCreatedAt: new Date('05.05.2000'),
    answerIndex: 0,
    // author
    authorIsLegalPerson: false,
    authorFirstName: 'John',
    authorLastName: 'Rich',
    authorShortName: null,
    authorEmail: 'testEmail@dewais.com',
    image: '00000000-test-image-uuid-000000000001',
  },
  {
    ...DTOPollData,
    uid: '00000000-aaaa-aaaa-aaaa-000000000001',
    title: 'Test title of poll #1 (created poll)',
    body: 'Test perfect body of poll #1 (created poll)',
    answerUid: '00000000-aaaa-aaaa-aabb-000000000002',
    answerTitle: 'test answer title 2',
    answerBasic: true,
    answerStatus: PollAnswerStatus.MODERATION,
    answerAuthorUID: publicUserData.uid,
    answerCreatedAt: new Date('05.05.2000'),
    answerIndex: 1,
    // author
    authorIsLegalPerson: false,
    authorFirstName: 'M2',
    authorLastName: 'V2',
    authorShortName: null,
    authorEmail: 'testEmailV2@dewais.com',
    image: '00000000-test-image-uuid-000000000001',
  },
  {
    ...DTOPollData,
    uid: '00000000-aaaa-aaaa-aaaa-000000000002',
    title: 'Test title of poll #2 (created poll)',
    body: 'Test perfect body of poll #2 (created poll)',
    answerUid: '00000000-aaaa-aaaa-aabb-000000000003',
    answerTitle: 'test answer title',
    answerBasic: true,
    answerStatus: PollAnswerStatus.PUBLISHED,
    answerAuthorUID: publicUserData.uid,
    answerCreatedAt: new Date('05.05.2000'),
    answerIndex: 0,
    // author
    authorIsLegalPerson: false,
    authorFirstName: 'John',
    authorLastName: 'Rich',
    authorShortName: null,
    authorEmail: 'testEmail@dewais.com',
    image: '00000000-test-image-uuid-000000000001',
  },
  {
    ...DTOPollData,
    uid: '00000000-aaaa-aaaa-aaaa-000000000002',
    title: 'Test title of poll #2 (created poll)',
    body: 'Test perfect body of poll #2 (created poll)',
    answerUid: '00000000-aaaa-aaaa-aabb-000000000004',
    answerTitle: 'test answer title 2',
    answerBasic: true,
    answerStatus: PollAnswerStatus.PUBLISHED,
    answerAuthorUID: publicUserData.uid,
    answerCreatedAt: new Date('05.05.2000'),
    answerIndex: 1,
    // author
    authorIsLegalPerson: false,
    authorFirstName: 'M4',
    authorLastName: 'V4',
    authorShortName: null,
    isHidden: false,
    authorEmail: 'testEmailForV4@dewais.com',
    image: '00000000-test-image-uuid-000000000001',
  },
]

const pollData = {
  anonymous: true,
  complexWorkflow: false,
  authorUID: publicUserData.uid,
  status: PollStatus.MODERATION,
  authorData: {
    isLegalPerson: false,
    firstName: 'John',
    lastName: 'Rich',
    shortName: null,
    avatar: null,
    email: 'testEmail@dewais.com',
  },
  tags: List([]),
  taGenders: List([]),
  taAgeGroups: List([]),
  competencyTags: List([]),
  taSocialStatuses: List([]),
  theme: Theme.AGRICULTURE,
  votingStartAt: new Date('01.02.2020'),
  votingEndAt: new Date('02.02.2020'),
  createdAt: undefined,
  discussionStartAt: undefined,
  taAddressDistrict: undefined,
  taAddressTown: undefined,
  publishedAt: undefined,
  answersCount: 0,
  votesCount: 0,
  commentsCount: 0,
  isHidden: false,
  taAddressRegion: Region.KHARKIV_REGION,
  pollType: PollType.REGULAR,
  image: '00000000-test-image-uuid-000000000001',
}

export const pollArray: Array<Poll> = [
  {
    ...pollData,
    uid: '00000000-aaaa-aaaa-aaaa-000000000001',
    title: 'Test title of poll #1 (created poll)',
    body: 'Test perfect body of poll #1 (created poll)',
    answers: List([]),
  },
  {
    ...pollData,
    uid: '00000000-aaaa-aaaa-aaaa-000000000002',
    title: 'Test title of poll #2 (created poll)',
    body: 'Test perfect body of poll #2 (created poll)',
    answers: List([
      {
        uid: '00000000-aaaa-aaaa-aabb-000000000003',
        title: 'test answer title',
        basic: true,
        status: PollAnswerStatus.PUBLISHED,
        authorUID: publicUserData.uid,
        createdAt: new Date('05.05.2000'),
        pollUID: '00000000-aaaa-aaaa-aaaa-000000000002',
        index: 0,
      },
      {
        uid: '00000000-aaaa-aaaa-aabb-000000000004',
        title: 'test answer title 2',
        basic: true,
        status: PollAnswerStatus.PUBLISHED,
        authorUID: publicUserData.uid,
        createdAt: new Date('05.05.2000'),
        pollUID: '00000000-aaaa-aaaa-aaaa-000000000002',
        index: 1,
      },
    ]),
  },
]
