import { Gender } from '../../../../src/iviche/common/Gender'
import { Language } from '../../../../src/iviche/common/Language'
import { Region } from '../../../../src/iviche/common/Region'
import { SocialStatus } from '../../../../src/iviche/common/SocialStatus'
import { UserRole } from '../../../../src/iviche/common/UserRole'
import { NotificationService } from '../../../../src/iviche/notification/services/NotificationService'
import { ProfileDTO } from '../../../../src/iviche/profiles/dto/ProfileDTO'
import { ProfileListDTO } from '../../../../src/iviche/profiles/dto/ProfileListDTO'
import { ProfileTuple } from '../../../../src/iviche/profiles/dto/ProfileTuple'
import { Profile } from '../../../../src/iviche/profiles/models/Profile'
import { UserSystemStatus } from '../../../../src/iviche/users/models/UserSystemStatus'

export const PhoneServiceMock: jest.Mock<NotificationService> = jest.fn().mockImplementation(() => {
  return {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    notify: jest.fn((service, notification) => {
      return
    }),
  }
})

export const profileDTO: ProfileDTO = {
  uid: '00000000-aaaa-aaaa-bbbb-000000000001',
  avatar: '00000000-aaaa-aaaa-bbbb-111111111111',
  addressRegion: Region.KYIV_CITY_REGION,
  addressDistrict: 'test1',
  addressTown: 'test1',
  bio: 'test1',
  birthdayAt: new Date('01.01.1900 GMT+00:00'),
  email: 'test1@gmail.com',
  firstName: 'test1',
  middleName: 'test1',
  lastName: 'test1',
  jobTitle: 'test1',
  shortName: 'test1',
  legalName: 'test1',
  phone: '+380963332211',
  socialStatus: SocialStatus.UNEMPLOYED,
  gender: Gender.MALE,
  tagline: 'test1',
  isLegalPerson: false,
  isPublicPerson: false,
  systemStatus: UserSystemStatus.ACTIVE,
  emailConfirmed: false,
  notifyEmail: false,
  notifySMS: false,
  notifyTelegram: false,
  notifyViber: false,
  notifyAboutNewPoll: false,
  facebookId: undefined,
  googleId: undefined,
  phoneConfirmed: false,
  role: UserRole.PRIVATE,
  username: 'test1@gmail.com',
  language: Language.UA,
}

export const singleProfile: Profile = {
  person: {
    avatar: '00000000-aaaa-aaaa-bbbb-111111111111',
    addressRegion: Region.KYIV_CITY_REGION,
    addressDistrict: 'test1',
    addressTown: 'test1',
    bio: 'test1',
    birthdayAt: new Date('01.01.1900 GMT+00:00'),
    email: 'test1@gmail.com',
    firstName: 'test1',
    middleName: 'test1',
    lastName: 'test1',
    jobTitle: 'test1',
    shortName: 'test1',
    legalName: 'test1',
    phone: '+380963332211',
    socialStatus: SocialStatus.UNEMPLOYED,
    gender: Gender.MALE,
    tagline: 'test1',

    isLegalPerson: false,
    isPublicPerson: false,
  },
  details: {
    emailConfirmed: false,
    notifyEmail: false,
    notifySMS: false,
    notifyTelegram: false,
    notifyViber: false,
    notifyAboutNewPoll: false,
    phoneConfirmed: false,
    wpJournalistID: undefined,
    googleId: undefined,
    appleId: undefined,
    facebookId: undefined,
    language: Language.UA,
  },
  user: {
    uid: '00000000-aaaa-aaaa-bbbb-000000000001',
    role: UserRole.PRIVATE,
    username: 'test1@gmail.com',
    password: '',
    systemStatus: UserSystemStatus.ACTIVE,
  },
}

export const publicUserProfile = {
  person: {
    addressRegion: Region.POLTAVA_REGION,
    addressDistrict: null,
    addressTown: 'hadiach_city',
    bio: null,
    birthdayAt: new Date('1990-04-14T12:51:21.189Z').toISOString(),
    email: 'grigory.skovoroda@iviche.com',
    firstName: 'Grigory',
    gender: Gender.MALE,
    isLegalPerson: false,
    isPublicPerson: true,
    jobTitle: null,
    lastName: 'Skovoroda',
    legalName: null,
    middleName: null,
    phone: '+380440001122#5',
    shortName: null,
    socialStatus: SocialStatus.CLERK,
    tagline: null,
    avatar: null,
  },
  user: {
    uid: '00000000-aaaa-aaaa-aaaa-000000000005',
    password: '',
    role: UserRole.PRIVATE,
    username: 'grigory.skovoroda@iviche.com',
    systemStatus: UserSystemStatus.ACTIVE,
  },
  details: {
    emailConfirmed: true,
    phoneConfirmed: true,
    notifyEmail: false,
    notifySMS: false,
    notifyTelegram: false,
    notifyViber: false,
    notifyAboutNewPoll: true,
    wpJournalistID: null,
    googleId: null,
    facebookId: null,
    appleId: null,
    language: Language.UA,
  },
}

export const listDtoProfiles: Array<ProfileTuple> = [
  {
    addressRegion: Region.KYIV_CITY_REGION,
    addressDistrict: 'test1',
    addressTown: 'test1',
    birthdayAt: new Date('01.01.1900 GMT+00:00'),
    email: 'test1@gmail.com',
    firstName: 'test1',
    middleName: 'test1',
    lastName: 'test1',
    jobTitle: 'test1',
    shortName: 'test1',
    legalName: 'test1',
    phone: '+380963332201',
    isLegalPerson: false,
    role: UserRole.PRIVATE,
    username: 'test1@gmail.com',
    createdAt: new Date('1900-01-01T00:00:00.000Z'),
  },
  {
    addressRegion: Region.KYIV_REGION,
    addressDistrict: 'test2',
    addressTown: 'test2',
    birthdayAt: new Date('01.01.1900 GMT+00:00'),
    email: 'test2@gmail.com',
    firstName: 'test2',
    middleName: 'test2',
    lastName: 'test2',
    jobTitle: 'test2',
    shortName: 'test2',
    legalName: 'test2',
    phone: '+380963332202',
    isLegalPerson: false,
    role: UserRole.PRIVATE,
    username: 'test2@gmail.com',
    createdAt: new Date('1900-01-01T00:00:00.000Z'),
  },
  {
    addressRegion: Region.CHERKASY_REGION,
    addressDistrict: 'test3',
    addressTown: 'test3',
    birthdayAt: new Date('01.01.1900 GMT+00:00'),
    email: 'test3@gmail.com',
    firstName: 'test3',
    middleName: 'test3',
    lastName: 'test3',
    jobTitle: 'test3',
    shortName: 'test3',
    legalName: 'test3',
    phone: '+380963332203',
    isLegalPerson: false,
    role: UserRole.PRIVATE,
    username: 'test3@gmail.com',
    createdAt: new Date('1900-01-01T00:00:00.000Z'),
  },
]

export const listProfiles: Array<ProfileListDTO> = [
  {
    person: {
      addressRegion: Region.KYIV_CITY_REGION,
      addressDistrict: 'test1',
      addressTown: 'test1',
      birthdayAt: new Date('01.01.1900 GMT+00:00'),
      email: 'test1@gmail.com',
      firstName: 'test1',
      middleName: 'test1',
      lastName: 'test1',
      jobTitle: 'test1',
      shortName: 'test1',
      legalName: 'test1',
      phone: '+380963332201',
      isLegalPerson: false,
    },
    user: {
      role: UserRole.PRIVATE,
      username: 'test1@gmail.com',
      password: '',
      createdAt: new Date('1900-01-01T00:00:00.000Z'),
    },
  },
  {
    person: {
      addressRegion: Region.KYIV_REGION,
      addressDistrict: 'test2',
      addressTown: 'test2',
      birthdayAt: new Date('01.01.1900 GMT+00:00'),
      email: 'test2@gmail.com',
      firstName: 'test2',
      middleName: 'test2',
      lastName: 'test2',
      jobTitle: 'test2',
      shortName: 'test2',
      legalName: 'test2',
      phone: '+380963332202',
      isLegalPerson: false,
    },
    user: {
      role: UserRole.PRIVATE,
      username: 'test2@gmail.com',
      password: '',
      createdAt: new Date('1900-01-01T00:00:00.000Z'),
    },
  },
  {
    person: {
      addressRegion: Region.CHERKASY_REGION,
      addressDistrict: 'test3',
      addressTown: 'test3',
      birthdayAt: new Date('01.01.1900 GMT+00:00'),
      email: 'test3@gmail.com',
      firstName: 'test3',
      middleName: 'test3',
      lastName: 'test3',
      jobTitle: 'test3',
      shortName: 'test3',
      legalName: 'test3',
      phone: '+380963332203',
      isLegalPerson: false,
    },
    user: {
      role: UserRole.PRIVATE,
      username: 'test3@gmail.com',
      password: '',
      createdAt: new Date('1900-01-01T00:00:00.000Z'),
    },
  },
]

export const ownProfileDTO: ProfileDTO = {
  uid: '00000000-aaaa-aaaa-bbbb-000000000002',
  addressRegion: Region.KYIV_CITY_REGION,
  addressDistrict: 'test1',
  addressTown: 'test1',
  bio: 'test1',
  birthdayAt: new Date('01.01.1900 GMT+00:00'),
  email: 'test1@gmail.com',
  firstName: 'test1',
  middleName: 'test1',
  lastName: 'test1',
  jobTitle: 'test1',
  shortName: 'test1',
  legalName: 'test1',
  phone: '+380963332211',
  socialStatus: SocialStatus.UNEMPLOYED,
  gender: Gender.MALE,
  tagline: 'test1',
  isLegalPerson: false,
  isPublicPerson: false,
  systemStatus: UserSystemStatus.ACTIVE,
  emailConfirmed: false,
  notifyEmail: false,
  notifySMS: false,
  notifyTelegram: false,
  notifyViber: false,
  notifyAboutNewPoll: false,
  phoneConfirmed: false,
  googleId: undefined,
  facebookId: undefined,
  role: UserRole.PRIVATE,
  username: 'test1@gmail.com',
  avatar: '00000000-aaaa-abbb-aaaa-000000000001',
  language: Language.UA,
}

export const ownProfile: Profile = {
  person: {
    avatar: '00000000-aaaa-abbb-aaaa-000000000001',
    addressRegion: Region.KYIV_CITY_REGION,
    addressDistrict: 'test1',
    addressTown: 'test1',
    bio: 'test1',
    birthdayAt: new Date('01.01.1900 GMT+00:00'),
    email: 'test1@gmail.com',
    firstName: 'test1',
    middleName: 'test1',
    lastName: 'test1',
    jobTitle: 'test1',
    shortName: 'test1',
    legalName: 'test1',
    phone: '+380963332211',
    socialStatus: SocialStatus.UNEMPLOYED,
    gender: Gender.MALE,
    tagline: 'test1',
    isLegalPerson: false,
    isPublicPerson: false,
  },
  details: {
    emailConfirmed: false,
    notifyEmail: false,
    notifySMS: false,
    notifyTelegram: false,
    notifyViber: false,
    notifyAboutNewPoll: false,
    phoneConfirmed: false,
    wpJournalistID: undefined,
    googleId: undefined,
    appleId: undefined,
    facebookId: undefined,
    language: Language.UA,
  },
  user: {
    uid: '00000000-aaaa-aaaa-bbbb-000000000002',
    role: UserRole.PRIVATE,
    username: 'test1@gmail.com',
    password: '',
    systemStatus: UserSystemStatus.ACTIVE,
  },
}

export const ownProfileForEmailUpdate: Profile = {
  person: {
    avatar: '00000000-aaaa-abbb-aaaa-000000000001',
    addressRegion: Region.KYIV_CITY_REGION,
    addressDistrict: 'test1',
    addressTown: 'test1',
    bio: 'test1',
    birthdayAt: new Date('01.01.1900 GMT+00:00'),
    email: 'test1@gmail.com',
    firstName: 'test1',
    middleName: 'test1',
    lastName: 'test1',
    jobTitle: 'test1',
    shortName: 'test1',
    legalName: 'test1',
    phone: '+380963332211',
    socialStatus: SocialStatus.UNEMPLOYED,
    gender: Gender.MALE,
    tagline: 'test1',
    isLegalPerson: false,
    isPublicPerson: false,
  },
  details: {
    emailConfirmed: false,
    notifyEmail: false,
    notifySMS: false,
    notifyTelegram: false,
    notifyViber: false,
    phoneConfirmed: false,
    emailConfirmationCode: 'test1 code',
    emailConfirmationCodeCreatedAt: new Date('01.01.1900 GMT+00:00'),
  },
  user: {
    uid: '00000000-aaaa-aaaa-bbbb-000000000001',
    role: UserRole.PRIVATE,
    username: 'test1@gmail.com',
    password: '',
    systemStatus: UserSystemStatus.ACTIVE,
  },
}

export const ownFBProfileForEmailUpdate: Profile = {
  person: {
    avatar: '00000000-aaaa-abbb-aaaa-000000000002',
    addressDistrict: 'test1',
    addressRegion: Region.KYIV_CITY_REGION,
    addressTown: 'test1',
    bio: 'test1',
    birthdayAt: new Date('01.01.1900 GMT+00:00'),
    email: 'test1@gmail.com',
    firstName: 'test1',
    middleName: 'test1',
    lastName: 'test1',
    jobTitle: 'test1',
    shortName: 'test1',
    legalName: 'test1',
    phone: '+380963332211',
    socialStatus: SocialStatus.UNEMPLOYED,
    gender: Gender.MALE,
    tagline: 'test1',
    isLegalPerson: false,
    isPublicPerson: false,
  },
  details: {
    emailConfirmed: true,
    notifyEmail: false,
    notifySMS: false,
    notifyTelegram: false,
    notifyViber: false,
    phoneConfirmed: false,
    emailConfirmationCode: 'test1 code',
    emailConfirmationCodeCreatedAt: new Date('01.01.1900 GMT+00:00'),
    facebookId: '1234567890',
  },
  user: {
    uid: '00000000-aaaa-aaaa-bbbb-000000000002',
    role: UserRole.PRIVATE,
    username: '1234567890@facebook',
    password: '',
    systemStatus: UserSystemStatus.ACTIVE,
  },
}
