export enum SocialStatus {
  CLERK = 'CLERK',
  WORKER = 'WORKER',
  MANAGER = 'MANAGER',
  UNEMPLOYED = 'UNEMPLOYED',
  SELFEMPLOYED = 'SELFEMPLOYED',
  STUDENT = 'STUDENT',
  RETIREE = 'RETIREE',
  UNKNOWN = 'UNKNOWN',
}
