export enum UserRole {
  ADMINISTRATOR = 'ADMINISTRATOR',
  MODERATOR = 'MODERATOR',
  JOURNALIST = 'JOURNALIST',
  PRIVATE = 'PRIVATE',
  LEGAL = 'LEGAL',
  ANONYMOUS = 'ANONYMOUS',
  DELETED = 'DELETED',
}
